### PR TITLE
Support tarball in S3

### PR DESCRIPTION
**Pull request by sfc-gh-kmakino**
This PR allows users to specify an S3 URL for `--tarball` argument.
When an S3 URL is specified, the package won't be copied into FDB. Instead, the agent directly downloads it from S3.

This PR introduces 2 behavior changes:
- AWS credentials must be properly setup on both the client and the agent
- `boto3` package is required

### CODE REVIEW

**Comment by ammolitor** [comment]
Looks like we need to add `boto3` to the `test-requirements.txt` file. 

Can we add a test to verify that both file formats still play nice?

**Comment by sfc-gh-kmakino** [comment]
@ammolitor Is there any s3 buckets that we can use to test this feature?
We've tested this manually against our own S3, but it cannot be used for CI testing.

**Comment by ammolitor** [comment]
> @ammolitor Are there any s3 buckets that we can use to test this feature?
> We've tested this manually against our own S3, but it cannot be used for CI testing.

Do we just need a bucket to hold a file for a test? Depending on the use case, I might be able to work something out. Public S3 objects are generally frowned upon now-a-days. 😁

**Comment by sfc-gh-kmakino** [comment]
@ammolitor Just added the test using the mocked S3. Please review it again. 🙏

**Review by ammolitor — APPROVED** [review]

**Pull request merged**
