### PR TITLE
add swift

### PR DESCRIPTION
**Pull request by ammolitor**
add the swift toolchain to the joshua-agent image

### CODE REVIEW

**Review by vishesh — APPROVED** [review]

**Review by ktoso — APPROVED** [review]
LGTM, thank you 👍

**Comment by sfc-gh-kmakino** [comment]
How large is the Swift toolchain that's included in the agant image?
I'm OK with this change, but in the long term, we'd better come up with a better way of managing external tools that are independent from the Joshua framework itself.

**Review by xis19 — APPROVED** [review]
lgtm

**Comment by ktoso** [comment]
As for installation method this is a bit ugly right now since Swift 5.9 which we depend on has not been released stable yet. Once it has, we'll be able to work on may be offering a package to install directly, or other streamlined methods (we have swiftly, a swift version manager/downloader as well). It would be also worth considering upgrading from CentOS7 eventually since it's EOL status 🤔 But we can definitely work on a better installation path, adding what's necessary in the official Swift repos etc 👍 Happy to revisit this once 5.9 is stable!

Hmmm, a "whole" slim docker image is 300mb or so, but that's the whole image. I've not measured how much exactly the minimal runtime bits are, we can check if necessary though the container already seems to have a lot of stuff there heh :)

**Pull request merged**
