### PR TITLE
Revert "Avoid overshooting"

### PR DESCRIPTION
**Pull request by sfc-gh-kmakino**
Reverts FoundationDB/fdb-joshua#49

Oh no, there was a bug somewhere.
It can go into a situation where idle agents doesn't get out.
I'm debugging.

### CODE REVIEW

**Comment by sfc-gh-kmakino** [comment]
I found a solution.

**Comment by xumengpanda** [comment]
Can you pls link the solution? :)

**Comment by sfc-gh-kmakino** [comment]
https://github.com/FoundationDB/fdb-joshua/pull/52

**Comment by sfc-gh-kmakino** [comment]
@xumengpanda Please revert this. I found another edge case. I'll spend more time to test this...  Sigh, I need Joshua for Joshua.

**Pull request merged**
